=== alinkamalinkakalinka/XML2RDF-DataTransformation-MappingTool/related-documentation/MappingLanguage_v1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 2 (http://www.altova.com) by Christos Georgis (Information Systems Laboratory) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>This XML Schema is based on Mapping Language defined in "Mapping Language for Information Integration" Technical Report 385, ICS-FORTH, December 2006</xs:documentation>
		<xs:documentation>Institute of Computer Science, FORTH-ICS, Heraklio, Crete, Greece: Maria Koutraki(kutraki@ics.forth.gr) , Martin Doerr(martin@ics.forth.gr)</xs:documentation>
		<xs:documentation>Last Update: 05-08-2010</xs:documentation>
		<xs:documentation>
			<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">
				<img alt="Άδεια Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/88x31.png"/>
			</a>
			<br/>Το <span xmlns:dc="http://purl.org/dc/elements/1.1/" href="http://purl.org/dc/dcmitype/Text" property="dc:title" rel="dc:type">Mapping Language for Information Integration</span> από τον <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.cidoc-crm.org/xsd/MappingLanguage_V1.0.xsd " property="cc:attributionName" rel="cc:attributionURL">Institute of Computer Science, FORTH-ICS, http://www.ics.forth.gr</a> This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-ShareAlike 3.0 Greece License </a>.
			</xs:documentation>
	</xs:annotation>
	<xs:element name="mapping">
		<!--Holds the mapping definition from mapping-scheme-1 to mapping-schema-2 e.g. Lido to CIDOC-CRM.-->
		<xs:complexType>
			<xs:sequence>
				<xs:element name="map" maxOccurs="unbounded">
					<!--One map element for each domain_map. -->
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="domain_map"/>
							<xs:element ref="link_map" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="domain_map">
		<!--Maps "src_domain" of  mapping-scheme-1 to "target_domain" of  mapping-schema-2. e.g. src_domain: lido element. target_domain: CIDOC class.-->
		<xs:complexType>
			<xs:sequence>
				<xs:element name="src_domain_condition" type="conditions" minOccurs="0"/>
				<xs:element name="src_domain" type="xs:string"/>
				<!-- from mapping-scheme-1  e.g. Lido element.-->
				<xs:element name="target_domain" type="xs:string"/>
				<!--to  mapping-schema-2 e.g. CODOC class.-->
				<xs:element ref="uri_rules"/>
				<xs:element ref="add_link" minOccurs="0"/>
				<xs:element ref="add_entity" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="link_map">
		<!--Holds "range_map" and "path_map".-->
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="range_map"/>
				<xs:element ref="path_map"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="range_map">
		<!--Maps source range to target range.-->
		<xs:complexType>
			<xs:sequence>
				<xs:element name="src_range_condition" type="conditions" minOccurs="0"/>
				<xs:element name="src_range" type="xs:string">
					<!-- example Lido element. eg."lido:lidoRecID".-->
				</xs:element>
				<xs:element name="target_range" type="xs:string">
					<!-- example CIDOC class. eg. "E31_Document".-->
				</xs:element>
				<xs:element ref="uri_rules"/>
				<xs:element ref="add_link" minOccurs="0"/>
				<xs:element ref="add_entity" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="path_map">
		<!--Maps source path to target path.-->
		<xs:complexType>
			<xs:sequence>
				<xs:element name="src_path" type="xs:string"/>
				<!-- example  Lido element. eg. "lidoRecID"-->
				<xs:element name="target_path">
					<!--The whole path that needs to be mapped to the "src_path".
										e.g In some cases target_path is a CIDOC property. In other cases is a CIDOC property a CIDOC class and another CIDOC property.-->
					<xs:complexType>
						<xs:sequence>
							<xs:element name="target_path_condition" type="conditions" minOccurs="0"/>
							<xs:element ref="int_link"/>
							<xs:element name="int_entity" type="xs:string" minOccurs="0"/>
							<!--e.g. CIDOC class.Intermediate node.-->
							<xs:element ref="uri_rules" minOccurs="0"/>
							<xs:element ref="add_link" minOccurs="0"/>
							<xs:element ref="add_entity" minOccurs="0"/>
							<xs:element ref="int_link" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="uri_rules">
		<xs:annotation>
			<xs:documentation/>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element name="uri_function" minOccurs="0">
					<!--Name and arguments for uri function.-->
					<xs:complexType>
						<xs:sequence minOccurs="0">
							<xs:element name="name" type="xs:string" minOccurs="0"/>
							<!--Uri function name.-->
							<xs:element name="arguments" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
							<!--Uri function arguments. In Xpath form e.g. from lido xml file.-->
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="conditions">
		<xs:sequence minOccurs="0">
			<xs:element ref="if" minOccurs="0"/>
			<xs:element ref="if_not" minOccurs="0"/>
			<xs:element ref="if_exist" minOccurs="0"/>
			<xs:element ref="if_not_exist" minOccurs="0"/>
			<xs:element ref="if_hasbroader" minOccurs="0"/>
			<xs:element ref="if_not_hasbroader" minOccurs="0"/>
			<xs:element name="AND" minOccurs="0" maxOccurs="unbounded">
				<!--"And" condition.-->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="condition1" type="conditions"/>
						<xs:element name="condition2" type="conditions"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="OR" minOccurs="0" maxOccurs="unbounded">
				<!--"Or" condition.-->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="condition1" type="conditions"/>
						<xs:element name="condition2" type="conditions"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="if" type="pathValue"/>
	<!--"if" condition.-->
	<xs:element name="if_not" type="pathValue"/>
	<!--"if not" condition.-->
	<xs:element name="if_exist" type="path"/>
	<!--"if exist" condition.-->
	<xs:element name="if_not_exist" type="path"/>
	<!--"if not exist" condition.-->
	<xs:element name="if_hasbroader" type="pathValue"/>
	<!--"if hasbroader" condition.-->
	<xs:element name="if_not_hasbroader" type="pathValue"/>
	<!--"if not hasbroader" condition.-->
	<xs:complexType name="pathValue">
		<xs:sequence minOccurs="0">
			<xs:element name="path" type="xs:string" minOccurs="0"/>
			<!--Specific path in Lido xml file.-->
			<xs:element name="has_value" type="xs:string" minOccurs="0"/>
			<!--Specific value to the "path" should have in the "if" case or should not have in the "if_not" case.-->
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="path">
		<xs:sequence minOccurs="0">
			<xs:element name="path" type="xs:string" minOccurs="0"/>
			<!--Specific Xpath e.g. xpath in Lido xml file.-->
		</xs:sequence>
	</xs:complexType>
	<xs:element name="add_link" type="xs:string">
	</xs:element>
	<xs:element name="add_entity">
		<!--Additional entity -->
		<xs:complexType>
			<xs:sequence>
				<xs:element name="value">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="value_binding" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="uri_rules"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="int_link" type="xs:string"/>
	<!--CIDOC property.-->
</xs:schema>

=== alinkamalinkakalinka/XML2RDF-DataTransformation-MappingTool/XML2RDF-DataTransformation-(MappingTool)-v3.3/examples-documentation/mappingVandaMaTh.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--This document defines a mapping from any xml to CIDOC-CRM v5.0.1. Based on Mapping Language defined in "Mapping Language for Information Integration" Technical Report 385, ICS-FORTH, December 2006-->
<!--Institute of Computer Science, FORTH-ICS, Heraklio, Crete, Greece: Evangelia Daskalaki(eva@ics.forth.gr) , Martin Doerr(martin@ics.forth.gr)-->
<mapping xsi:noNamespaceSchemaLocation="MappingLanguage_v1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<map>
		<!-- RecID -->
		<domain_map>
			<src_domain>/rmxml/mus_catalogue</src_domain>
			<target_domain>E22_Man_Made_Object</target_domain>
			<uri_rules> 
				<uri_function>
					<!--<name>uuid</name>-->
					<name>uriPhysThing</name>
					<arguments>//variant_key/_/text()</arguments>
				</uri_function>
			</uri_rules>
		</domain_map>
		
		<link_map>
			<range_map>
			
				<src_range>//variant_key/_</src_range>
				<target_range>E22_Man_Made_Object</target_range>
				<uri_rules>
					<uri_function>
						<name>uriPhysThing</name>
						<arguments>text()</arguments>
					</uri_function>
				</uri_rules>
			</range_map> 		
			<path_map>
				<src_path>//variant_key/_</src_path>
				<target_path>
					<int_link>is composed of</int_link>
				</target_path>
			</path_map> 
			
		</link_map>
		<link_map>
			<range_map>
				<src_range>//mus_object_name/_</src_range>
				<target_range>Literal</target_range>
				<uri_rules>
					<uri_function>
						<name>uriPhysThing</name>
						<arguments>text()</arguments>
					</uri_function>
				</uri_rules>
			</range_map> 		
			<path_map>
				<src_path>//mus_object_name/_</src_path>
				<target_path>
					<int_link>crmdig:L4F.has_preferred_label</int_link>
				</target_path>
			</path_map> 	
		</link_map>
		<link_map>
			<range_map>
				<src_range>//vanda_museum_number</src_range>
				<target_range>Literal</target_range>
				<uri_rules>
					<uri_function>
						<name>createLiteral</name>
						<arguments>text()</arguments>
					</uri_function>
				</uri_rules>
			</range_map> 		
			<path_map>
				<src_path>//vanda_museum_number</src_path>
				<target_path>
					<int_link>crmdig:L4F.has_inventory_no</int_link>
				</target_path>
			</path_map> 	
		</link_map>	
		
	</map>
	
	
	
	
	
	<map>
		<!-- RecID -->
		<domain_map>
			<src_domain>/rmxml/mus_catalogue/mus_part</src_domain>
			<target_domain>E22_Man_Made_Object</target_domain>
			<uri_rules> 
				<uri_function>
					<!--<name>uuid</name>-->
					<name>uriPhysThing</name>
					<arguments>//_/mus_part_obj_num/mus_part_obj_num_display/text()</arguments>
				</uri_function>
			</uri_rules>
		</domain_map>
		
		<link_map>
			<range_map>
			
				<src_range>//_/mus_part_name/_/mus_part_name_field/mus_part_name_field_val</src_range>
				<target_range>E55.Type</target_range>
				<uri_rules>
					<uri_function>
						<name>uriPhysThing</name>
						<arguments>text()</arguments>
					</uri_function>
				</uri_rules>
			</range_map> 		
			<path_map>
				<src_path>//_/mus_part_name/_/mus_part_name_field/mus_part_name_field_val</src_path>
				<target_path>
					<int_link>P3.has_type</int_link>
				</target_path>
			</path_map> 
			
		</link_map>
	</map>
</mapping>

=== alinkamalinkakalinka/XML2RDF-DataTransformation-MappingTool/XML2RDF-DataTransformation-(MappingTool)-v3.3/examples-documentation/mappingVandaMaTh1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--This document defines a mapping from any xml to CIDOC-CRM v5.0.1. Based on Mapping Language defined in "Mapping Language for Information Integration" Technical Report 385, ICS-FORTH, December 2006-->
<!--Institute of Computer Science, FORTH-ICS, Heraklio, Crete, Greece: Evangelia Daskalaki(eva@ics.forth.gr) , Martin Doerr(martin@ics.forth.gr)-->
<mapping xsi:noNamespaceSchemaLocation="MappingLanguage_v1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<map>
		<!-- RecID -->
		<domain_map>
			<src_domain>/rmxml/mus_catalogue</src_domain>
			<target_domain>http://www.ics.forth.gr/isl/rdfs/3D-COFORM_CIDOC-CRM.rdfs#E22_Man_Made_Object</target_domain>
			<uri_rules> 
				<uri_function>
					<name>uuid</name>
					<!--<name>uriPhysThing</name>-->
					<!--<arguments>//variant_key/_/text()</arguments>-->
				</uri_function>
			</uri_rules>
		</domain_map>
		
		<link_map>
			<range_map>
			
				<src_range>//variant_key/_</src_range>
				<target_range>http://www.ics.forth.gr/isl/rdfs/3D-COFORM_CIDOC-CRM.rdfs#E22_Man_Made_Object</target_range>
				<uri_rules>
					<uri_function>
						<name>uriPhysThing</name>
						<arguments>text()</arguments>
					</uri_function>
				</uri_rules>
			</range_map> 		
			<path_map>
				<src_path>//variant_key/_</src_path>
				<target_path>
					<int_link>http://www.ics.forth.gr/isl/rdfs/3D-COFORM_CIDOC-CRM.rdfs#P46F.is_composed_of</int_link>
				</target_path>
			</path_map> 
			
		</link_map>
		
		<link_map>
			<range_map>
				<src_range>//vanda_museum_number</src_range>
				<target_range>Literal</target_range>
				<uri_rules>
					<uri_function>
						<name>createLiteral</name>
						<arguments>text()</arguments>
					</uri_function>
				</uri_rules>
			</range_map> 		
			<path_map>
				<src_path>//vanda_museum_number</src_path>
				<target_path>
					<int_link>http://www.ics.forth.gr/isl/rdfs/3D-COFORM_CRMdig.rdfs#L4F.has_inventory_no</int_link>
				</target_path>
			</path_map> 	
		</link_map>	
		
	</map>
	
</mapping>

=== alinkamalinkakalinka/XML2RDF-DataTransformation-MappingTool/XML2RDF-DataTransformation-(MappingTool)-v3.3/examples-documentation/eva/mappingVanda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--This document defines a mapping from any xml to CIDOC-CRM v5.0.1. Based on Mapping Language defined in "Mapping Language for Information Integration" Technical Report 385, ICS-FORTH, December 2006-->
<!--Institute of Computer Science, FORTH-ICS, Heraklio, Crete, Greece: Evangelia Daskalaki(eva@ics.forth.gr) , Martin Doerr(martin@ics.forth.gr)-->
<mapping xsi:noNamespaceSchemaLocation="MappingLanguage_v1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<map>
		<!-- RecID -->
		<domain_map>
			<src_domain>/root/aspect</src_domain>
			<target_domain>E22_Man_Made_Object</target_domain>
			<uri_rules> 
				<uri_function>
					<!--<name>uuid</name>-->
					<name>uriForPhysicalObjects</name>
					<arguments>./_/variant_key/text()</arguments>
					<arguments>./_/variant_key/text()</arguments>
				</uri_function>
			</uri_rules>
		</domain_map>
		<link_map>
			<range_map>
			<!-- To src_range einai panta relative tou src_domain mesa sto xml arxeio-->
				<src_range>//aspect_parts_part</src_range>
				<target_range>E22_Man_Made_Object</target_range>
				<uri_rules>
					<uri_function>
						<name>uriForPhysicalObjects</name>
						<arguments>./text()</arguments>
						<arguments>./text()</arguments>
					</uri_function>
				</uri_rules>
			</range_map> 		
			<path_map>
				<src_path>//aspect_parts_part</src_path>
				<target_path>
					<int_link>P46_is_composed_of</int_link>
				</target_path>
			</path_map> 
			
		</link_map>
		<link_map>
			<range_map>
				<src_range>//aspect_parts_part</src_range>
				<target_range>E22_Man_Made_Object</target_range>
				<uri_rules>
					<uri_function>
						<name>uriForPhysicalObjects</name>
						<arguments>./text()</arguments>
						<arguments>./text()</arguments>
					</uri_function>
				</uri_rules>
			</range_map> 		
			<path_map>
				<src_path>//aspect_parts_part</src_path>
				<target_path>
					<int_link>P46_is_part_of</int_link>
				</target_path>
			</path_map> 
			
		</link_map>
	</map>
		<map>
		<!-- RecID -->
		<domain_map>
			<src_domain>/root/aspect</src_domain>
			<target_domain>E22_Man_Made_Object</target_domain>
			<uri_rules> 
				<uri_function>
					<!--<name>uuid</name>-->
					<name>uriForPhysicalObjects</name>
					<arguments>./_/variant_key/text()</arguments>
					<arguments>./_/variant_key/text()</arguments>
				</uri_function>
			</uri_rules>
		</domain_map>

		<link_map>
			<range_map>
				<src_range>//aspect_parts_part</src_range>
				<target_range>E22_Man_Made_Object</target_range>
				<uri_rules>
					<uri_function>
						<name>uriForPhysicalObjects</name>
						<arguments>./text()</arguments>
						<arguments>./text()</arguments>
					</uri_function>
				</uri_rules>
			</range_map> 		
			<path_map>
				<src_path>//aspect_parts_part</src_path>
				<target_path>
					<int_link>P46_is_nnnn_of</int_link>
				</target_path>
			</path_map> 
			
		</link_map>
	</map>

</mapping>
